const data = {
  products: [
    {
      name: 'Testing Prodct 1',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'first-product',
    },
    {
      name: 'Testing Prodct 2',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'second-product',
    },
    {
      name: 'Testing Prodct 3',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'third-product',
    },
    {
      name: 'Testing Prodct 4',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'fourth-product',
    },
    {
      name: 'Testing Prodct 5',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'fifth-product',
    },
    {
      name: 'Testing Prodct 6',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'sixth-product',
    },
    {
      name: 'Testing Prodct 7',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'seventh-product',
    },
    {
      name: 'Testing Prodct 8',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'eighth-product',
    },
    {
      name: 'Testing Prodct 9',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'nineth-product',
    },
    {
      name: 'Testing Prodct 10',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'tenth-product',
    },
    {
      name: 'Testing Prodct 11',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'eleventh-product',
    },
    {
      name: 'Testing Prodct 12',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'twelth-product',
    },
    {
      name: 'Testing Prodct 13',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'thrtin-product',
    },
    {
      name: 'Testing Prodct 14',
      description: 'This is testing product',
      amount: '15000',
      image: 'https://wea.maurya.games/uploads/images/51iEBQzCL5L._UL1500_.jpg',
      slug: 'forthen-product',
    },
  ],
};

export default data;
